apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    persistentvolumeclaim.name: data-rabbit-rabbitmq-0
  name: data-rabbit-rabbitmq-0
spec:
  volumeName: rabbit-volume
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi