apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    persistentvolumeclaim.name: redis-data-redis-master-0
  name: redis-data-redis-master-0
spec:
  volumeName: redis-master-volume
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-replicas-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    persistentvolumeclaim.name: redis-data-redis-replicas-0
  name: redis-data-redis-replicas-0
spec:
  volumeName: redis-replicas-volume
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi